### ISSUE TITLE
Launcher is Folio ready

### ISSUE THREAD

**Issue by keathleydavidj** [bigtestjs/cli#32]
We want to be able to use the launch in the Folio ecosystem. In order to do that we need... 

- [ ] Supports code-coverage metrics
- [ ] Has a J-Unit reporter
- [ ] Can't be crashing all the time
- [ ] Has to support browser-stack
- [ ] (Stretch-goal) Would be great to have a console dashboard
